// Mock mech data for development and testing

export const MOCK_MECHS = [
  {
    id: 'mech-1',
    name: 'Atlas',
    variant: 'AS7-D',
    tonnage: 100,
    baseBV: 1897,
    weapons: ['AC/20', 'LRM-20', '4x Medium Laser', 'SRM-6'],
    role: 'Juggernaut',
    armor: 307,
    speed: 3,
    jumpJets: 0,
    ownedCount: 1
  },
  {
    id: 'mech-2',
    name: 'Timber Wolf',
    variant: 'TBR-Prime',
    tonnage: 75,
    baseBV: 2370,
    weapons: ['2x ER Large Laser', '2x LRM-20', '4x Machine Gun', '2x Medium Pulse Laser'],
    role: 'Skirmisher',
    armor: 211,
    speed: 5,
    jumpJets: 0,
    ownedCount: 2
  },
  {
    id: 'mech-3',
    name: 'Locust',
    variant: 'LCT-1V',
    tonnage: 20,
    baseBV: 356,
    weapons: ['2x Machine Gun', 'Medium Laser'],
    role: 'Scout',
    armor: 48,
    speed: 8,
    jumpJets: 0,
    ownedCount: 0
  },
  {
    id: 'mech-4',
    name: 'Marauder',
    variant: 'MAD-3R',
    tonnage: 75,
    baseBV: 1543,
    weapons: ['2x PPC', 'AC/5', '2x Medium Laser'],
    role: 'Sniper',
    armor: 200,
    speed: 4,
    jumpJets: 0,
    ownedCount: 1
  },
  {
    id: 'mech-5',
    name: 'Jenner',
    variant: 'JR7-D',
    tonnage: 35,
    baseBV: 669,
    weapons: ['4x Medium Laser', 'SRM-4'],
    role: 'Striker',
    armor: 104,
    speed: 7,
    jumpJets: 5,
    ownedCount: 0
  },
  {
    id: 'mech-6',
    name: 'Hunchback',
    variant: 'HBK-4G',
    tonnage: 50,
    baseBV: 1021,
    weapons: ['AC/20', '2x Medium Laser'],
    role: 'Brawler',
    armor: 152,
    speed: 4,
    jumpJets: 0,
    ownedCount: 1
  },
  {
    id: 'mech-7',
    name: 'Catapult',
    variant: 'CPLT-C1',
    tonnage: 65,
    baseBV: 1319,
    weapons: ['2x LRM-15', '4x Medium Laser'],
    role: 'Missile Boat',
    armor: 192,
    speed: 4,
    jumpJets: 0,
    ownedCount: 0
  },
  {
    id: 'mech-8',
    name: 'Warhammer',
    variant: 'WHM-6R',
    tonnage: 70,
    baseBV: 1299,
    weapons: ['2x PPC', '2x Medium Laser', 'SRM-6', '2x Small Laser'],
    role: 'Sniper',
    armor: 184,
    speed: 4,
    jumpJets: 0,
    ownedCount: 1
  },
  {
    id: 'mech-9',
    name: 'Commando',
    variant: 'COM-2D',
    tonnage: 25,
    baseBV: 471,
    weapons: ['SRM-6', '2x Medium Laser'],
    role: 'Striker',
    armor: 64,
    speed: 6,
    jumpJets: 0,
    ownedCount: 0
  },
  {
    id: 'mech-10',
    name: 'Awesome',
    variant: 'AWS-8Q',
    tonnage: 80,
    baseBV: 1605,
    weapons: ['3x PPC', 'Small Laser'],
    role: 'Sniper',
    armor: 216,
    speed: 3,
    jumpJets: 0,
    ownedCount: 1
  },
  {
    id: 'mech-11',
    name: 'Shadow Hawk',
    variant: 'SHD-2H',
    tonnage: 55,
    baseBV: 918,
    weapons: ['AC/5', 'LRM-5', 'Medium Laser', 'SRM-2'],
    role: 'Skirmisher',
    armor: 152,
    speed: 5,
    jumpJets: 3,
    ownedCount: 1
  },
  {
    id: 'mech-12',
    name: 'Archer',
    variant: 'ARC-2R',
    tonnage: 70,
    baseBV: 1353,
    weapons: ['2x LRM-20', '4x Medium Laser'],
    role: 'Missile Boat',
    armor: 200,
    speed: 4,
    jumpJets: 0,
    ownedCount: 0
  }
];
